#a=input("DIGITE ALGO:")
#print(type(a))
#print(a.isnumeric())
#print(a.isalnum())
#print(a.isalpha())

a=input("Digite algo:")
print("O tipo primitivo desse valor é", type(a))
print("Só tem epaços?", a.isspace())
print("É um número?", a.isnumeric())
print("É uma palavra?", a.isalpha())
print("É alphanumérico?", a.isalnum())
print("Está em minúscula?", a.islower())
print("Está em maiuscula?", a.isupper())
